apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
    - name: secret-test
      image: nginx
      
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: password