apiVersion: v1
kind: Pod
metadata:
  name: env-pod1
spec:
  containers:
    - name: nginx2
      image: nginx
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: secret-fish
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: password        